# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4dd776d0d4d27d6f66befa248c2601162372a70c42843013505c857b9baa6d72b0648f0fdb68956e0fcde63ebf3ab7900ec3b7c28dd76f0eb7f50f979608edd5

test:
  secret_key_base: eb1c8c6e453b170054e5c82607c83feba4ca4028bf43b7cd33693f6cfc9cfe456ba04e11617e2594a2901cb1d59d9b2b6358a6a6b99d9fff5e531a1035e86460

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
